[project]
name = "woman"
version = "0.2.1"
description = "A CLI tool that describes Unix commands using the Gemini API"
authors = [
    { name="Fardix", email="Fardixxx@proton.me" }
]
dependencies = ["requests", "colorama"]
requires-python = ">=3.7"

[project.scripts]
woman = "woman.__main__:main"
